name: evoliving
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  form_inputs:
    git: https://github.com/ISL270/form_inputs
  formz: ^0.8.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  lottie: ^3.3.0
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0
  injectable: ^2.5.0
  dartx: ^1.2.0
  equatable: ^2.0.7
  theme_tailor_annotation: ^3.1.2
  theme_tailor: ^3.1.2
  fpdart: ^1.1.1
  bloc_concurrency: ^0.2.5
  very_good_analysis: ^7.0.0
  go_router: ^14.8.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  gap: ^3.0.1
  animate_do: ^4.2.0
  app_settings: ^5.2.0
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  isar: ^3.1.0+1 
  isar_flutter_libs: ^3.1.0+1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.6.2
  source_gen: ^4.1.1   # الإصدار المتاح فعلاً :contentReference[oaicite:3]{index=3}
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svgs/
